branches:
  except:
    - donttestme

dist: xenial
language: bash
sudo: required

services:
  - docker

install:
  - travis_retry travis_wait make build-no-cache

script:
  - make generate-accounts run generate-accounts-after-run fixtures tests

after_script:
  - make clean

after_success:
  - >
    test "$DOCKERHUB_TRIGGER_URL" -a -z "$TRAVIS_PULL_REQUEST_BRANCH" &&
    curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "'$TRAVIS_BRANCH'"}'
    -X POST $DOCKERHUB_TRIGGER_URL
