branches:
  except:
    - donttestme
dist: xenial
language: bash
sudo: required
services:
  - docker
install:
  - sudo apt-get install -y python3-venv
  - travis_retry travis_wait make build-no-cache
script:
  - ./run_tests.sh
  - make generate-accounts run generate-accounts-after-run fixtures tests
after_script:
  - make clean
  - test $DOCKER_URL && curl -XPOST "$DOCKER_URL"
